# This file was generated by the Tkinter Designer by Parth Jadhav
# https://github.com/ParthJadhav/Tkinter-Designer
import sys
from pathlib import Path
from tkinter import Tk, Canvas, Entry, Text, Button, PhotoImage
from vampyro import *
import random

OUTPUT_PATH = Path(__file__).parent
if hasattr(sys, '_MEIPASS'):
    # Quando rodando como executável
    ASSETS_PATH = Path(sys._MEIPASS) / "build" / "assets" / "frame0"
else:
    # Quando rodando como script Python
    ASSETS_PATH = OUTPUT_PATH / "build" / "assets" / "frame0"

def relative_to_assets(path: str) -> Path:
    return ASSETS_PATH / Path(path)


def gerar_ficha_completa():
    entry_3.delete("1.0", "end")  # Limpa o campo de texto

    # Obtém os valores dos campos de entrada
    nome = entry_1.get().strip().title()
    cla = entry_2.get().strip().title()

    # Define valores padrão caso os campos estejam vazios
    if not nome:
        nome = "Cainita"
    if not cla:
        cla = random.choice(list(lista_cla.keys()))
    if cla not in lista_cla:
        # Exibe a lista de clãs no campo de texto
        entry_3.insert("1.0", "Clã inválido! Escolha um dos seguintes clãs:\n\n")
        for cl in lista_cla.keys():
            entry_3.insert("end", f"{cl}\n")
        return  # Sai da função sem continuar

    # Cria o objeto Vampiro usando a classe
    vampiro = Vampiro(nome=nome, cla=cla)

    # Exibe os dados do Vampiro na GUI
    entry_3.insert("1.0", f"Nome: {vampiro.nome}\nClã: {vampiro.cla}\nGeração: {vampiro.geracao}\n\n")
    entry_3.insert("end", "Atributos:\n")
    for categoria, atributos in vampiro.atributos.items():
        entry_3.insert("end", f"\n{categoria.capitalize()}:\n")
        atributos_lista = list(atributos.items())
        for i in range(0, len(atributos_lista), 3):
            linha = atributos_lista[i:i+3]
            linha_formatada = " | ".join(f"{atributo.capitalize()}: {valor}" for atributo, valor in linha)
            entry_3.insert("end", f"{linha_formatada}\n")

    entry_3.insert("end", "\nHabilidades:\n")
    for categoria, habilidades in vampiro.habilidades.items():
        habilidades_filtradas = {k: v for k, v in habilidades.items() if v > 0}
        if habilidades_filtradas:
            entry_3.insert("end", f"\n{categoria.capitalize()}:\n")
            habilidades_lista = list(habilidades_filtradas.items())
            for i in range(0, len(habilidades_lista), 3):
                linha = habilidades_lista[i:i+3]
                linha_formatada = " | ".join(f"{habilidade.capitalize()}: {valor}" for habilidade, valor in linha)
                entry_3.insert("end", f"{linha_formatada}\n")

    entry_3.insert("end", "\nAntecedentes:\n")
    antecedentes_filtrados = {k: v for k, v in vampiro.antecedentes.items() if v > 0}
    if antecedentes_filtrados:
        antecedentes_lista = list(antecedentes_filtrados.items())
        for i in range(0, len(antecedentes_lista), 3):
            linha = antecedentes_lista[i:i+3]
            linha_formatada = " | ".join(f"{antecedente.capitalize()}: {valor}" for antecedente, valor in linha)
            entry_3.insert("end", f"{linha_formatada}\n")

    entry_3.insert("end", "\nVirtudes:\n")
    virtudes_lista = list(vampiro.virtudes.items())
    for i in range(0, len(virtudes_lista), 3):
        linha = virtudes_lista[i:i+3]
        linha_formatada = " | ".join(f"{virtude.capitalize()}: {valor}" for virtude, valor in linha)
        entry_3.insert("end", f"{linha_formatada}\n")

    entry_3.insert("end", "\nQualidades e Defeitos:\n")
    qed_lista = list(vampiro.qed.items())
    for i in range(0, len(qed_lista), 3):
        linha = qed_lista[i:i+3]
        linha_formatada = " | ".join(f"{qed.capitalize()}: {valor}" for qed, valor in linha)
        entry_3.insert("end", f"{linha_formatada}\n")

    entry_3.insert("end", "\nDisciplinas:\n")
    disciplinas_lista = list(vampiro.disciplinas.items())
    for i in range(0, len(disciplinas_lista), 3):
        linha = disciplinas_lista[i:i+3]
        linha_formatada = " | ".join(f"{disciplina.capitalize()}: {valor}" for disciplina, valor in linha)
        entry_3.insert("end", f"{linha_formatada}\n")

    entry_3.insert("end", f"\nTrilha: {vampiro.humanidade}\n")
    entry_3.insert("end", f"Força de Vontade: {vampiro.forca_de_vontade}\n")
    entry_3.insert("end", f"Pontos de Sangue: {vampiro.pontos_de_sangue}\n")


def copiar_para_area_de_transferencia():
    # Obtém o texto do campo de texto
    texto = entry_3.get("1.0", "end").strip()
    if texto:  # Verifica se há texto para copiar
        window.clipboard_clear()  # Limpa a área de transferência
        window.clipboard_append(texto)  # Adiciona o texto à área de transferência
        window.update()  # Atualiza a área de transferência


window = Tk()
window.title("VamPYro - V3")

icon_image = PhotoImage(file=relative_to_assets("icon.png"))  # Substitua "icon.png" pelo nome do arquivo do ícone
window.iconphoto(False, icon_image)

window.geometry("845x480")
window.configure(bg = "#00183E")


canvas = Canvas(
    window,
    bg = "#00183E",
    height = 480,
    width = 845,
    bd = 0,
    highlightthickness = 0,
    relief = "ridge"
)

canvas.place(x = 0, y = 0)
canvas.create_rectangle(
    0.0,
    0.0,
    845.0,
    75.0,
    fill="#001736",
    outline="")

image_image_1 = PhotoImage(
    file=relative_to_assets("image_1.png"))
image_1 = canvas.create_image(
    422.0,
    240.0,
    image=image_image_1
)

button_image_1 = PhotoImage(
    file=relative_to_assets("button_1.png"))
button_1 = Button(
    image=button_image_1,
    borderwidth=0,
    highlightthickness=0,
    command=lambda: exibir_creditos(entry_3),
    relief="flat"
)
button_1.place(
    x=753.0,
    y=17.0,
    width=64.0,
    height=15.0
)

canvas.create_text(
    21.0,
    205.0,
    anchor="nw",
    text="Clã",
    fill="#FFFFFF",
    font=("Inter SemiBoldItalic", 15 * -1)
)

canvas.create_text(
    21.0,
    99.0,
    anchor="nw",
    text="Nome",
    fill="#FFFFFF",
    font=("Inter SemiBoldItalic", 15 * -1)
)

entry_image_1 = PhotoImage(
    file=relative_to_assets("entry_1.png"))
entry_bg_1 = canvas.create_image(
    95.0,
    144.0,
    image=entry_image_1
)
entry_1 = Entry(
    bd=0,
    bg="#D9D9D9",
    fg="#000716",
    highlightthickness=0
)
entry_1.place(
    x=21.0,
    y=125.0,
    width=148.0,
    height=36.0
)

entry_image_2 = PhotoImage(
    file=relative_to_assets("entry_2.png"))
entry_bg_2 = canvas.create_image(
    95.0,
    250.0,
    image=entry_image_2
)
entry_2 = Entry(
    bd=0,
    bg="#D9D9D9",
    fg="#000716",
    highlightthickness=0
)
entry_2.place(
    x=21.0,
    y=231.0,
    width=148.0,
    height=36.0
)

entry_image_3 = PhotoImage(
    file=relative_to_assets("entry_3.png"))
entry_bg_3 = canvas.create_image(
    452.5,
    246.0,
    image=entry_image_3
)
entry_3 = Text(
    bd=0,
    bg="#FFEABF",
    fg="#000716",
    highlightthickness=0
)
entry_3.place(
    x=191.0,
    y=31.0,
    width=523.0,
    height=428.0
)

button_image_2 = PhotoImage(
    file=relative_to_assets("button_2.png"))
button_2 = Button(
    image=button_image_2,
    borderwidth=0,
    highlightthickness=0,
    command=gerar_ficha_completa,  # Agora executa a função de gerar ficha
    relief="flat"
)
button_2.place(
    x=56.0,
    y=294.0,
    width=77.0,
    height=23.0
)

button_image_3 = PhotoImage(
    file=relative_to_assets("button_3.png"))
button_3 = Button(
    image=button_image_3,
    borderwidth=0,
    highlightthickness=0,
    command=copiar_para_area_de_transferencia,  # Agora copia o texto
    relief="flat"
)
button_3.place(
    x=743.0,
    y=438.0,
    width=77.0,
    height=23.0
)

image_image_2 = PhotoImage(
    file=relative_to_assets("image_2.png"))
image_2 = canvas.create_image(
    94.0,
    41.0,
    image=image_image_2
)

canvas.create_text(
    149.0,
    55.0,
    anchor="nw",
    text="V3",
    fill="#FFFFFF",
    font=("Inter Italic", 12 * -1)
)
window.resizable(False, False)
window.mainloop()
